### ISSUE TITLE
Shim and module code function differently for OVERRIDE type

### ISSUE THREAD

**Issue by itamarcu** [ruipin/fvtt-lib-wrapper#1]
In the shim code, functions are called like this:
```js
obj[fn_name] = function() { return fn.call(this, original, ...arguments); };
```

In the module code they're called like this:

```js
result = fn.call(obj, next_fn, ...args);
```

*except* if they're OVERRIDE type, in which case they're called like this:

```js
return fn.apply(obj, args);
```

This breaks the behavior of shimmed override functions (e.g. in my module, [ZoomPanOptions](https://github.com/itamarcu/ZoomPanOptions)) when the module exists. The `next_fn` argument is not passed.

**Comment by itamarcu** [comment]
I believe the fix is to add a `type` argument to the shim `register` function, and if that type is override, to call fn without the `original` argument.

**Comment by ruipin** [comment]
You are completely right, this was an oversight from my end.

Originally, the `OVERRIDE` type would also receive the `next_fn` argument. This was changed later on, but by then I had already written the shim, and forgot to change the test-case for it.

v1.0.3 fixes this, by properly checking the `type` parameter for `OVERRIDE`. It also tweaks the test cases to ensure that this situation ('OVERRIDE' with parameters) is correctly tested.

Thanks for the report, and sorry for any inconvenience!
