### ISSUE TITLE
new update breaks foundry with Alternative rotation 

### ISSUE THREAD

**Issue by GuineaThePig** [ruipin/fvtt-lib-wrapper#10]
trying to draw something or create a wall fails with no error message while alternative rotation and the latest version of lib-wrapper are on. tested with only these two modules on while on a new campaign

**Comment by ruipin** [comment]
Thanks for the report, and sorry for any inconvenience I might have caused.

I've reverted the changes that caused this in v1.1.4.0 while I work on debugging this.
