### ISSUE TITLE
Latest update conflicts with Scene Clicker

### ISSUE THREAD

**Issue by JamzTheMan** [ruipin/fvtt-lib-wrapper#11]
Having this module activated with Scene Clicker prevents Actor sheets from opening from the sidebar.

Not sure if this is a Scene Clicker issue or libWrapper but I narrowed down the issue only persists if I have both activated and just started after latest lib wrapper update...

**Comment by ruipin** [comment]
Thanks for the report, and sorry for any inconvenience I might have caused.

I've reverted the changes that caused this in v1.1.4.0 while I work on debugging this.

**Comment by 4535992** [comment]
Related to the current problem, here a issue i have verified with the new TidySheet version 0.4.1 https://github.com/sdenec/tidy5e-sheet/issues/169

**Comment by ruipin** [comment]
Yeah, that is caused by a bug in libWrapper. Sorry about that, working on it!
