### ISSUE TITLE
"Statistics collection is disabled" for players

### ISSUE THREAD

**Issue by astromind** [ruipin/fvtt-lib-wrapper#26]
### Steps to reproduce:
In foundry settings - `Permission configuration` page give `Player` or `Trusted player` group the `Modify configuration settings` permission.
Login as (trusted) player.
Open libWrapper settings.

### Observed:
User can't modify libWrapper settings.`Priorities` and `Conflicts` tabs are empty. "Statistics collection is disabled" message is displayed.
### Expected:
User, who is given access to libWrapper settings, should be able to change them.

**Comment by ruipin** [comment]
Statistics collection is disabled for any non-GM user, as the assumption was they would not need to modify these settings anyway, and there's a tiny performance impact.

I had not thought about the "Modify configuration settings" permission. Thanks for the report.

**Comment by ruipin** [comment]
This is now fixed in [v1.4.0.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.4.0.0), closing.

Feel free to re-open if the issue (or something similar) still occurs.
