### ISSUE TITLE
breaks norc's custom hotbar somehow, or maybe custom hotbar breaks libwrapper?

### ISSUE THREAD

**Issue by EsotericOdyssey** [ruipin/fvtt-lib-wrapper#29]
I can run norc's custom hotbar and any number of other modules that don't need libwrapper just fine but if I try to run custom hotbar and libwrapper together the game gets stuck loading at 100% and the console keeps spitting out thousands of messages about trying to load custom hotbar

**Comment by ruipin** [comment]
Thanks for the report. I'm now looking into this.

Since https://github.com/ruipin/fvtt-lib-wrapper/issues/30 has more comments, I'm consolidating the v1.4.0.0 breakages on there. Closing this one as duplicate.
