### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by caewok** [ruipin/fvtt-lib-wrapper#34]
Foundry 0.7.9, lib wrapper 1.5.3.0, dnd5e 1.2.4.
Server: docker image on VM running Ubuntu
Browser: Safari Technical Preview, Release 123 (Safari 14.2, WebKit 16612.1.7.10), on macOS 11.3.1

**Disclaimer**

Yes, I know Foundry doesn't actively support Safari. But please, hear me out... Foundry runs well on Safari Technical Preview, and on macOS, Safari is dramatically faster than Chrome or Firefox. I mean, sometimes double the framerate on an older laptop. And this particular issue, I think, involves the lib wrapper shim, so it breaks a lot of modules.

**Issue**
When using lib wrapper alone, or using other modules that use the default lib wrapper shim code, I see this error in the console:

> SyntaxError: Invalid regular expression: invalid group specifier name

The result is that lib wrapper doesn't load, nor do other modules that use that shim. Nor do modules that depend on libwrapper. So this error has rather large consequences to getting Foundry to work in Safari. 

**Proposed Solution**

I think this error is due to the fact that [Safari does not accept negative or positive lookahead regex expressions](https://caniuse.com/js-regexp-lookbehind). See t[his StackOverflow question](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group) or [this one](https://stackoverflow.com/questions/56926806/how-to-make-this-regex-safari-ios-compliant) for examples. 

Specifically, this regex in [shim.js](https://github.com/ruipin/fvtt-lib-wrapper/blob/master/shim/shim.js) may need to be changed in order to work in Safari:
`const MODULE_ID = ((import.meta?.url ?? Error().stack)?.match(/(?<=\/)modules\/.+(?=\/)/i)??[])[0]?.split('/')?.find(n => n && game.modules.has(n));`

If that can be changed to not use the positive lookbehind, then hopefully lib wrapper will load on Safari, and other modules can adopt the change as well in their shim.

Thanks!

**Comment by ruipin** [comment]
Hmm, I'm actually no longer certain why I used a positive look-behind here. It could easily be replaced by a `\/`.

Guess there's no harm in doing it, even if Safari isn't officially supported.

**Comment by caewok** [comment]
I can confirm that lib-wrapper now loads in Safari Tech Preview without this error. Thanks!
