### ISSUE TITLE
Libwrapper ReferenceError: ace is not defined

### ISSUE THREAD

**Issue by mvanduijvenvoorde** [ruipin/fvtt-lib-wrapper#37]
Hi, I get the following errors after logging in FoundryVTT in my world:

**FoundryVTT**: 0.7.10
**DnD5e**: 1.
**Libwrapper**: 1.6.0

````
VM755:8 ReferenceError: ace is not defined
    at editor.js:5
    at Array.forEach (<anonymous>)
    at editor.js:5
    at Function._call (eval at <anonymous> (libWrapper-errors.js:249), <anonymous>:4:14)
    at Function.callAll (foundry.js:2456)
    at Game.initialize (foundry.js:6457)
    at z.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:448)
    at Game.🎁libWrapperInit (libWrapper-api.js:521)
    at Game.🎁Game.prototype.initialize#0 (libWrapper-wrapper.js:142)
    at window.addEventListener.once (foundry.js:7449)
_call @ VM755:8
quick-insert.ts:68 Uncaught (in promise) ReferenceError: KeybindLib is not defined
    at quick-insert.ts:68
    at Function._call (eval at <anonymous> (libWrapper-errors.js:249), <anonymous>:4:14)
    at Function.callAll (foundry.js:2456)
    at Game.initialize (foundry.js:6457)
    at z.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:448)
    at Game.🎁libWrapperInit (libWrapper-api.js:521)
    at Game.🎁Game.prototype.initialize#0 (libWrapper-wrapper.js:142)
    at window.addEventListener.once (foundry.js:7449)
````

**Active module list:**
about-time--v0.8.4;
ActiveAuras--v0.2.11;
animated-spell-effects--v0.6.5;
blood-n-guts--v0.8.7;
calendar-weather--v3.1.2;
coloredeffects--v0.0.7;
combat-utility-belt--v1.4.0;
CommunityLighting--v0.3.3;
compendium-folders--v2.2.44;
conditional-visibility--v0.1.4;
condition-automation--v3.0.0;
blind-roll-skills--v0.7.0;
custom-hotbar--v2.1.0;
custom-nameplates--v1.0.2;
Custom-Token-Animations--v0.1.20;
darkraven-games-soundscapes-free--v1.0.1;
deprecated-modules--v1.1.3;
dice-so-nice--v3.3.4;
dice-calculator--v0.6.8;
dnd5e-helpers--v2.0.3;
drag-ruler--v1.7.2;
Dynamic-Effects-SRD--v4.1.13;
dae--v0.2.62;
dynamic-illumination--v0.9.0;
EasyTable--v1.3.2;
easy-target--v2.11;
forien-copy-environment--v1.1.1;
forien-scene-navigator--v0.1.6;
foundry_community_macros--v0.40;
foundry_community_tables--v0.13;
free-loot-tavern-compendium--v1.9.1;
fxmaster--v1.0.3;
gm-notes--v0.4;
gm-screen--v2.4.3;
healthEstimate--v2.4.0;
launchmacro--v1.3.3;
illandril-chat-enhancements--v1.1.5;
illandril-hotbar-uses--v2.3.3;
illandril-token-hud-scale--v1.3.3;
image-hover--v1.1.7;
itemacro--vv1.5.1;
jb2a_patreon--v0.2.0;
colorsettings--v2.5.9;
_chatcommands--v1.3.3;
lib-df-hotkeys--v2.3.4;
lib-wrapper--v1.6.1.0;
LockView--v1.4.10;
long-rest-hd-healing--v2.2.0;
macroeditor--v1.0.7;
maestro--v0.7.4;
magicitems--v2.0.8;
_mathjs--v7.5.1-fvtt2;
max-crit--v0.1.7;
michaelghelfi--v1.2;
midi-qol--v0.3.103;
monsterblock--v2.4.7;
multilevel-tokens--v1.4.2;
Next-Up--v0.0.59;
perfect-vision--v1.9.4;
permission_viewer--v0.8.5;
pings--v1.2.11;
quick-insert--v2.4.7;
raise-my-hand--v1.1.0;
scene-transitions--v0.1.3;
settings-extender--v1.1.5;
SharedVision--v1.0.4;
alt5e--v1.5.2;
socketlib--v1.0.6;
_sortablejs--v1.10.2-fvtt1;
SoundBoard--v1.5.1;
tension-pool--v0.0.30;
Tetra-Cube-Importer--v1.1.0;
furnace--vv2.6.0;
tidy-ui_game-settings--v0.1.23;
times-up--v0.1.5;
token-action-hud--v1.0.22;
token-attacher--v4.0.2;
tokenmagic--v0.5.0;
rolladvantage-token-stamp-2-foundry--v1.1.2;
token-vision-animation-world--v1.0.0;
torch--v1.1.4;
trigger-happy--v0.8.2;
turnAlert--v1.5.1;
VoiceActor--v0.0.9;

**Comment by mvanduijvenvoorde** [comment]
I fixed it by activating the Ace and KeyLib module!

**Comment by ruipin** [comment]
Good to see you've solved it. As you probably realized, this error had nothing to do with libWrapper. It was present in the call-stack, but the issue was caused by a separate module.
