### ISSUE TITLE
"Failed to initialise Plutonium!" On forge.vtt

### ISSUE THREAD

**Issue by hdelane0** [ruipin/fvtt-lib-wrapper#38]
"libWrapper: Can't wrap 'Token.prototype._onUpdateTokenActor', target does not exist or could not be found."
![image](https://user-images.githubusercontent.com/64972269/120725356-c3493400-c4a3-11eb-8700-4d5efb3b5c59.png)
Not sure what this really means or how to fix it.

**Comment by ruipin** [comment]
As the error message says very prominently in the first line, this is an error with a module that uses libWrapper, not libWrapper itself.

You probably should start by reporting this issue to the creators of said module, especially considering the module in question.

For reference, the error is complaining that said module is trying to wrap the method "Token.prototype._onUpdateTokenActor", but this method does not exist in the version of Foundry you are currently running. This indicates to me that this module does not yet support said version of Foundry.

Closing this issue as invalid.
