### ISSUE TITLE
Full vs Shim compatibility

### ISSUE THREAD

**Issue by sneat** [ruipin/fvtt-lib-wrapper#43]
Hi,

I'm the author of [Scene Packer](https://github.com/League-of-Foundry-Developers/scene-packer) and currently include your shim but not a hard dependency.

I've been asked whether it's possible to remove the popup dialog that's bundled in the shim. I know it's possible, but I want to know what the differences currently are between the full module and the shim version. I can't see an issue or wiki entry that lists the differences and only one issue from several months ago (#3) that discusses differences.

My current thought is to use the shim that you provide, but remove the popup dialog, therefore using the full module if it's enabled but not prompting people if it isn't. What functionality would be lost with this approach though?

**Comment by ruipin** [comment]
I probably should add a much more detailed explanation of the differences between the full library and the shim in the documentation. I'll keep this ticket open until I find time to do it, so I don't forget.

Regarding your question about disabling the warning dialog, as you seem to be aware, yes you can strip the corresponding part of the code (second half of the shim) and no functionality is compromised. It was written on purpose assuming some people might not wish for that notification to be there.

With regards to the difference in functionality, but in essence the shim does standard javascript wrapping, and nothing else.

1. Shim does not support any user-facing functionality. Think prioritization of modules, conflict detection, etc. Basically, anything you can access through the libWrapper settings menu.

2. Shim does not support `libWrapper.unregister` calls.

3. Shim does not support dynamic dispatch. The wrapper chain is calculated at the time of the `register` call, and never changed later. This has many implications:

    1. The wrapper type metadata (`WRAPPER`, `MIXED`, `OVERRIDE`) is completely ignored. The wrapper call order will match the order in which they are registered. For instance, if a module registers an `OVERRIDE` after your module, you will never be called. Nobody guarantees `MIXED` wrappers comes after all `WRAPPER` wrappers.

    2. Inheritance chains are static. If you have `class B extends A` and override `B.prototype.foo` before someone else overrides `A.prototype.foo`, calling `B.prototype.foo` will skip the `A.prototype.foo` wrapper.

    3. There is no distinction between a libWrapper (Shim) wrapper and a non-libWrapper wrapper. While normally non-libWrapper wrappers will always come after all libWrapper wrappers, when using the shim this is not the case.

These are probably the most relevant differences. In essence, using the shim does not give you any advantage when it comes to compatibility versus not using libWrapper at all. As soon as two modules wrap the same thing, it is very likely things will break.

**Comment by ruipin** [comment]
I have now updated the [shim documentation](https://github.com/ruipin/fvtt-lib-wrapper/blob/50342b95201dbe4747c93d769b6624c407c6a49b/shim/SHIM.md#12-differences-compared-to-the-full-library) with the above information.

Closing this ticket. Feel free to open if if the above (or the documentation changes) did not answer all your questions.

**Comment by sneat** [comment]
Thanks @ruipin 👍
