### ISSUE TITLE
How to reference game system defined classes

### ISSUE THREAD

**Issue by tposney** [ruipin/fvtt-lib-wrapper#46]
How do I wrap a game system specific class's method. I would like to wrap ActorSheet5e _prepareArmorClassAttribution.
I tried going through CONFIG.Actor.sheetclasses; 
```
CONFIG.Actor.sheetClasses.character["dnd5e.ActorSheet5eCharacter"].cls.prototype._prepareArmorClassAttribution
```
which points to the correct method, but libwrapper rejects the string

**Comment by ruipin** [comment]
I was not aware that some classes are hidden behind arrays that contain `.`.

By default, you can access arrays just by the standard dot-notation, e.g. `A["abc"]` would be equivalent to `A.abc`. However, if the array index contains a dot, libWrapper will think those correspond to two different indexes. For example, `A["abc.def"]` is not equivalent to `A.abc.def`, as that would correspond to `A["abc"]["def"]`. This is why the above does not work.

I will look into adding support for actual array notation ASAP.

**Comment by ruipin** [comment]
I just realised that ActorSheet5eCharacter is exposed in `CONFIG.Actor.sheetClasses.character`, so that is probably the preferred way to reach it, at least until I add support for array indexing.

**Comment by ruipin** [comment]
[v1.8.0.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.8.0.0) adds support for string Array indexes. Make sure to check the documentation for details, specifically https://github.com/ruipin/fvtt-lib-wrapper/commit/fdf69602159ac4359db10ae09b9b08a3c07ba5e7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R289-R293

**Comment by tposney** [comment]
Wow that was fast. Many thanks that's great.

**Comment by tposney** [comment]
And works perfectly
