### ISSUE TITLE
It's breaking the auto crit damage from mid qol

### ISSUE THREAD

**Issue by dsakura** [ruipin/fvtt-lib-wrapper#5]
FVTT 0.7.9 (node)
DnD5e System 1.2.0
libWrapper 1.0.5.3
Compatibily erro with Midi QOL 0.3.43
I tried to reinstall both modules and without success, I know it depends on the other module and the problem may be in it, if it is the case I will report to the author of mid qol but I thought it opportune to warn.
Thank you

**Comment by ruipin** [comment]
> Compatibily erro with Midi QOL 0.3.43

What do you mean with this? Is there an actual error message? An error in the console?
If the module simply doesn't work, it's more likely to be an issue with the module itself.

**Comment by dsakura** [comment]
There is no error on the console. With the use of the libWrapper module, the additional damage from the critical hit does not occur automatically as before. When disabled it it works again. I tested using only the two modules at the same time, uninstalling both and reinstalling.
If there is anything I can do to better check the source of the error I try. It probably happened when I updated one of the modules, or both. I sent a message to the author of mid qol too, since I can't see on the console where the error is.
Thank you

**Comment by ruipin** [comment]
Yeah, please do report this to the module author. They are probably best positioned to figure out what is wrong, and if necessary report a libWrapper issue to me.

Might also be worth trying out today's libWrapper update v1.0.7.0. While I doubt the new changes won't fix this issue, there is a possibility they could.

**Comment by dsakura** [comment]
Alright! Thank you, sorry for any inconvenience

**Comment by ruipin** [comment]
I'll close this for now, especially considering #7 has been created by the author of midi-qol.
