### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WThunderspirit** [ruipin/fvtt-lib-wrapper#69]
⚠ Most errors triggered by libWrapper are not caused by libWrapper itself, but by a module/package. Do not open a support ticket using this form unless you are seeing an **internal** libWrapper error or are a **package developer** who needs support. We also do not provide support for packages that promote or otherwise endorse piracy. Your issue will be closed as invalid if you do not fulfill these requirements.

The easiest way to find support is to ask the community. The largest community-provided support channels are:
- [FoundryVTT Discord](https://discord.gg/foundryvtt)'s #modules-troubleshooting channel
- [FoundryVTT Reddit](https://www.reddit.com/r/FoundryVTT)

--------------------

**Confirm you have read the above**
Confirmed.  This seems to be a simple fix of changing "author" to "authors" in the module, per console log. 

**Describe the bug**
"1 compatability warnings detected with installed Packages.  Consult your console log (F12) for details."

**To Reproduce**
1. Install module libWrapper
2. Run the client
3. Get Error
4. Press F12

**Expected behavior**
No compatability warnings

**Screenshots**
![lib-wrapper](https://user-images.githubusercontent.com/107325064/188152089-76c39824-f35f-41eb-a62d-15900d7901ab.jpg)

**Technical Details (please complete the following information):**
 - LibWrapper Version [e.g. `1.6.1.0`, `1.7.2.0`, etc] 1.12.7.1
 - FoundryVTT Version [e.g. `0.7.10`, `0.8.6`, etc]  v10 b284
 - Browser & Version [e.g. "Official Client", "Chrome 91", "Firefox 89", etc] in the client (Foundry VTT)

**Additional context**
Simple Version 9 to 10 crossover fix to re-establish compatibility

**Comment by ruipin** [comment]
Thanks for this, I was unaware this was reported as a warning.

**Comment by ruipin** [comment]
Resolved in [v1.12.7.2](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.12.7.2), closing.
