### ISSUE TITLE
Error-Warnings due to v9 style data access

### ISSUE THREAD

**Issue by wickermoon** [ruipin/fvtt-lib-wrapper#71]
**Confirm you have read the above**
After reading the above, very briefly explain why this is the proper channel for asking for support.
I always create an issue for my pull requests.

**What do you need**
A clear and concise description of what you need.
I need those error-warnings to disappear. I created a PR that is switching data access in libWrapper from v9 style ".data" to v10 style direct access.

**Comment by ruipin** [comment]
Thanks a lot for the report!

I've released [v1.12.8.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.12.8.0) which contains shim version v1.12.2 which gets rid of these warnings, maintaining compatibility with older FVTT versions.
