### ISSUE TITLE
[BUG] Info from `Hooks.onError` getting lost

### ISSUE THREAD

**Issue by Ethaks** [ruipin/fvtt-lib-wrapper#76]
**Describe the bug**
Having libWrapper active changes contents of errors logged via `Hooks.onError`, leading to error information being removed.

**To Reproduce**
Run the following snippet in a console:
```js
try {
  const foo = null;
  foo.bar = false;
} catch (e) {
  Hooks.onError("Test function", e, {
    msg: "Something's wrong",
    log: "error",
  });
}
```

**Expected behavior**
The expected error message by default Foundry looks like this (i.e. includes the `msg` given to `Hooks.onError`): 
![default](https://user-images.githubusercontent.com/589855/215290067-4c38c896-c033-4a43-879d-89fc1962a233.png)

**Screenshots**
The error with libWrapper active looks like this:
![libWrapper](https://user-images.githubusercontent.com/589855/215290043-a15bb67a-70ea-45d7-8c0f-da5742244899.jpg)

**Technical Details (please complete the following information):**
 - LibWrapper Version `1.12.11.0`
 - FoundryVTT Version `10.291`
 - Browser & Version `Chrome 108`

**Comment by ruipin** [comment]
LibWrapper wraps Hooks.onError to add the list of affected packages to the error.

This is probably a bug with that piece of code. I'll take a look once I'm back home on Monday.

Thanks for the report, I was unaware of this difference in behaviour!

**Comment by ruipin** [comment]
This seems to occur anytime something causes the error to generate the corresponding stack message (in the `stack` property). Once that happens, the stack (which is what is displayed to the user) permanently copies the current error message.

The browser delays this until someone reads it. LibWrapper modifies this property to inject the package list, causing the stack to be generated before the `Something's wrong` message is prepended to the error message.

You can reproduce this without libWrapper by setting a breakpoint in the `onError` function, before `msg` is prepended to `error.message`. In such a case, the browser debugger causes `error.stack` to be generated with the improper message.

I'll see if I can implement a workaround.

**Comment by ruipin** [comment]
Workaround added in [v1.12.12.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.12.12.0). Closing issue.
