### ISSUE TITLE
Include version numbers in "package detection errors"

### ISSUE THREAD

**Issue by dmrickey** [ruipin/fvtt-lib-wrapper#80]
Right now if a problem is detected, it gives output like: `[Detected 3 packages: system:the-system, lib-wrapper, the-mod]`

If a user is reporting a problem, it can be hard to know exactly what's going on if the user's versions aren't up to date and they're using an outdated version of the mod and/or system. It would be very helpful if libwrapper could report the version numbers in the error message. So something like: `[Detected 3 packages: system:the system(v10.2), lib-wrapper(v1.12.13.1), the-mod(v1.3.0)]`

**Comment by ruipin** [comment]
I was trying to avoid adding too much text, but this shouldn't be hard to do and I guess it doesn't increase the text size too much...

The code that handles this is in https://github.com/ruipin/fvtt-lib-wrapper/blob/master/src/errors/error-utils.js#L52-L66 and the package version can be accessed through `package.version` (it is an accessor of the `PackageInfo` type).

**Comment by ruipin** [comment]
Added in [v1.12.14.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.12.14.0), specifically commit 23df043916bd6d044268bd4c1f50c76a55057bc0

**Comment by dmrickey** [comment]
Thanks! I think this will be very useful <3
