### ISSUE TITLE
[BUG]  Foundry V12 Depreciation Warnings

### ISSUE THREAD

**Issue by ottyn** [ruipin/fvtt-lib-wrapper#81]
⚠ Most errors triggered by libWrapper are not caused by libWrapper itself, but by a module/package. Do not open a support ticket using this form unless you are seeing an **internal** libWrapper error or are a **package developer** who needs support. We also do not provide support for packages that promote or otherwise endorse piracy. Your issue will be closed as invalid if you do not fulfill these requirements.

The easiest way to find support is to ask the community. The largest community-provided support channels are:
- [FoundryVTT Discord](https://discord.gg/foundryvtt)'s #modules-troubleshooting channel
- [FoundryVTT Reddit](https://www.reddit.com/r/FoundryVTT)

--------------------

**Confirm you have read the above**
After speaking with multiple module devs, they all point to the console warnings being from libWrapper and not their own modules.  Currently getting about 30 of these messages in console on world load from any module that has libWrapper as a dependency.

**Describe the bug**
Depreciation warning messages in console

**To Reproduce**
1. Happens on World load

**Screenshots**

![image](https://github.com/ruipin/fvtt-lib-wrapper/assets/97130150/6f2e192a-eb97-49ca-a51b-8b9bc5d9ec2e)

**Technical Details (please complete the following information):**
 - LibWrapper Version 1.12.13.1
 - FoundryVTT Version 12.328
 - Browser & Version: Chrome 126.0.6478.127

**Comment by ruipin** [comment]
Fixed in [v1.12.14.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.12.14.0), specifically commit cf068d4747cb4a1d5458a6d58af69bad0d6e2930
