### ISSUE TITLE
[BUG] Manifest warning

### ISSUE THREAD

**Issue by ddbrown30** [ruipin/fvtt-lib-wrapper#82]
The "libWrapper" module's manifest contained the following unknown keys: "author"

**Comment by Razytos** [comment]
Made a pull request for this, don't know if it will be merged.

**Comment by SirBedwyr** [comment]
I am now getting this warning as of Foundry 12.331 and libWrapper 1.12.13.1. Full text of warning: "The "libWrapper" module's manifest contained the following unknown keys: "author""
